public class TerneryOperatorForApptitude1{
	public static void main(String argv[]){
		 // System.out.println(false?76.8:98);//gives 98.0 because changed according to double.
	//float result1 = true?34.4:56;	//CTE
	//int result1 = false ? 't':67;//gives 67 if true then gives ASCII code of t=116.
	//char result1= true ? 56.5 : 34;  CTE possible lossy conversion from double to char.
	//char result1 = true?45v :65; //gives '-' symbil
	System.out.println("Hello Deepak patre")?45:65;
	
	System.out.println();
	}//End of main method.
}//End of class.