/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstguiapplication;

/**
 *
 * @author DEEPAK PATRE
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GreetButton = new javax.swing.JButton();
        TextLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GreetButton.setBackground(new java.awt.Color(51, 153, 0));
        GreetButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        GreetButton.setForeground(new java.awt.Color(255, 255, 255));
        GreetButton.setText("Click Here");
        GreetButton.setAlignmentY(0.0F);
        GreetButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        GreetButton.setBorderPainted(false);
        GreetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GreetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreetButtonMouseClicked(evt);
            }
        });
        GreetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GreetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 127, 56));

        TextLable.setBackground(new java.awt.Color(255, 255, 255));
        TextLable.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TextLable.setForeground(new java.awt.Color(21, 3, 42));
        getContentPane().add(TextLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 480, 85));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GreetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreetButtonMouseClicked
             TextLable.setText("       Helllo, World!!(:");
    }//GEN-LAST:event_GreetButtonMouseClicked

    private void GreetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreetButtonActionPerformed

    }//GEN-LAST:event_GreetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GreetButton;
    private javax.swing.JLabel TextLable;
    // End of variables declaration//GEN-END:variables
}
